# PY101
## Problem 4

What does this return and why? What concept does this cover?

```python
def convert_to_int(string):
    try:
        converted_integer = int(string)
        return converted_integer
    except ValueError:
        return "That string cannot be converted to an integer"
print(convert_to_int("hello"))
print(convert_to_int("5"))
```

<details>
<summary>Solution:</summary>

The `convert_to_int` function takes one string argument and attempts to convert it to an integer using a `try/except` block to handle potential `ValueErrors`. The first call with `"hello"` raises a `ValueError` because the string cannot be converted to an integer, so the `except` block is executed, and the function returns the string `"That string cannot be converted to an integer"`. The second call with `"5"` successfully converts the string to an integer `5`, which is then returned. The `print` function then implicitly coerces the integer `5` back into a string for output.

Concepts covered: Explicit and implicit type coercion, `try/except` blocks, and `ValueErrors`.

</details>

---

[Previous](003.md) | [Next](005.md)
